In [1]:
import numpy as np
from scipy import stats
import pandas as pd

In [19]:
#step 1 : creating a contingency tabe:
data ={'Category A':[70,75,80],
       'Category B':[50,70,75],
       'Category C':[60,65,70]}
contingency_table = pd.DataFrame(data,index=['Group 1',' Group 2',' Group 3'])

In [20]:
#step 2: Perform the chi-squared test
chi2_statistic,p_value,dof,expected=stats.chi2_contingency(contingency_table)

In [21]:
alpha =0.05

In [22]:
print(f'chi-squared statistics:{chi2_statistic:.4f}')
print(f'P-value:{p_value:.4f}')
print(f'Degrees of freedom:{dof:.4f}')
print(f'ExpectedFrequencies:\n{expected}')

chi-squared statistics:1.8222
P-value:0.7684
Degrees of freedom:4.0000
ExpectedFrequencies:
[[65.85365854 57.07317073 57.07317073]
 [76.82926829 66.58536585 66.58536585]
 [82.31707317 71.34146341 71.34146341]]


In [23]:
if p_value <alpha:
    print('Reject H0')
else:
    print('Fail to reject H0')

Fail to reject H0
